from alembic import op
import sqlalchemy as sa
revision='0001'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('users',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('email',sa.String(255),nullable=False),sa.Column('username',sa.String(100),nullable=False),sa.Column('display_name',sa.String(120),nullable=False),sa.Column('password_hash',sa.String(512),nullable=False),sa.Column('timezone',sa.String(80),nullable=False),sa.Column('language',sa.String(20),nullable=False),sa.Column('theme',sa.String(20),nullable=False),sa.Column('avatar_path',sa.String(500)),sa.Column('created_at',sa.DateTime(timezone=True)))
    op.create_index('ix_users_email','users',['email'],unique=True); op.create_index('ix_users_username','users',['username'],unique=True)
    op.create_table('sessions',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE')),sa.Column('token_hash',sa.String(128),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True)))
    op.create_index('ix_sessions_user_id','sessions',['user_id']); op.create_index('ix_sessions_token_hash','sessions',['token_hash'],unique=True); op.create_index('ix_sessions_expires_at','sessions',['expires_at'])
    op.create_table('conversations',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE')),sa.Column('conversation_type',sa.String(20),nullable=False),sa.Column('title',sa.String(255),nullable=False),sa.Column('archived',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True)),sa.Column('updated_at',sa.DateTime(timezone=True))); op.create_index('ix_conversations_user_id','conversations',['user_id']); op.create_index('ix_conversations_conversation_type','conversations',['conversation_type'])
    op.create_table('messages',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('conversation_id',sa.Integer(),sa.ForeignKey('conversations.id',ondelete='CASCADE')),sa.Column('role',sa.String(20),nullable=False),sa.Column('content',sa.Text(),nullable=False),sa.Column('provider',sa.String(100)),sa.Column('model',sa.String(150)),sa.Column('created_at',sa.DateTime(timezone=True))); op.create_index('ix_messages_conversation_id','messages',['conversation_id'])
    op.create_table('providers',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE')),sa.Column('company',sa.String(80),nullable=False),sa.Column('provider_type',sa.String(80),nullable=False),sa.Column('display_name',sa.String(120),nullable=False),sa.Column('model',sa.String(160),nullable=False),sa.Column('base_url',sa.String(500)),sa.Column('encrypted_credential',sa.Text()),sa.Column('priority',sa.Integer(),nullable=False),sa.Column('enabled',sa.Boolean(),nullable=False),sa.Column('preferred',sa.Boolean(),nullable=False),sa.Column('capabilities',sa.JSON(),nullable=False),sa.Column('health',sa.String(30),nullable=False),sa.Column('last_tested_at',sa.DateTime(timezone=True)),sa.Column('latency_ms',sa.Float()),sa.Column('usage_source',sa.String(20),nullable=False)); op.create_index('ix_providers_user_id','providers',['user_id'])
    op.create_table('capsules',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('conversation_id',sa.Integer(),sa.ForeignKey('conversations.id',ondelete='CASCADE')),sa.Column('version',sa.Integer(),nullable=False),sa.Column('data',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True))); op.create_index('ix_capsules_conversation_id','capsules',['conversation_id'])
    op.create_table('switch_events',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('conversation_id',sa.Integer(),sa.ForeignKey('conversations.id',ondelete='CASCADE')),sa.Column('from_provider',sa.String(100)),sa.Column('to_provider',sa.String(100),nullable=False),sa.Column('reason',sa.String(255),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True))); op.create_index('ix_switch_events_conversation_id','switch_events',['conversation_id'])
    op.create_table('alerts',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE')),sa.Column('severity',sa.String(20),nullable=False),sa.Column('title',sa.String(160),nullable=False),sa.Column('message',sa.Text(),nullable=False),sa.Column('source',sa.String(80),nullable=False),sa.Column('read',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True))); op.create_index('ix_alerts_user_id','alerts',['user_id'])
    op.create_table('files',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE')),sa.Column('original_name',sa.String(255),nullable=False),sa.Column('stored_name',sa.String(255),nullable=False),sa.Column('mime',sa.String(120),nullable=False),sa.Column('size',sa.Integer(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True))); op.create_index('ix_files_user_id','files',['user_id']); op.create_index('ix_files_stored_name','files',['stored_name'],unique=True)
    op.create_table('projects',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE')),sa.Column('name',sa.String(160),nullable=False),sa.Column('overview',sa.Text(),nullable=False),sa.Column('requirements',sa.JSON(),nullable=False),sa.Column('tasks',sa.JSON(),nullable=False),sa.Column('decisions',sa.JSON(),nullable=False),sa.Column('bugs',sa.JSON(),nullable=False),sa.Column('notes',sa.JSON(),nullable=False),sa.Column('memory',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True)))
    op.create_index('ix_projects_user_id','projects',['user_id'])
def downgrade():
    for t in ['projects','files','alerts','switch_events','capsules','providers','messages','conversations','sessions','users']: op.drop_table(t)
